services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
    ports:
      - '9411:9411'
    networks:
      - weather-tracing
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  goapp-b:
    container_name: goapp-b
    hostname: goapp-b
    build:
      context: ./service_b
      dockerfile: Dockerfile
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - '8081:8081'
    networks:
      - weather-tracing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  goapp-a:
    container_name: goapp-a
    hostname: goapp-a
    build:
      context: ./service_a
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - zipkin
      - goapp-b
    networks:
      - weather-tracing

networks:
  weather-tracing:
    driver: bridge
