scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']

  - job_name: 'cep-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['cep-service:8080']

  - job_name: 'weather-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['weather-service:8081']
